from evaluations.models import Section, Question

# EXAMPLE Section(section_name='Display', section_order=6),
def bulk_add_sections():
    Section.objects.bulk_create([
         Section(section_name='Admin/Business', section_order=1),
         Section(section_name='Analytics', section_order=2),
         Section(section_name='Billing', section_order=3),
         Section(section_name='Data/DMP', section_order=4),
         Section(section_name='Forecasting', section_order=5),
         Section(section_name='Mobile', section_order=6),
         Section(section_name='Mobile Reporting', section_order=7),
         Section(section_name='Native', section_order=8),
         Section(section_name='Native Reporting', section_order=9),
         Section(section_name='Omni-channel', section_order=10),
         Section(section_name='Omni-channel reporting', section_order=11),
         Section(section_name='Private Marketplace', section_order=12),
         Section(section_name='Service: Knowledge base', section_order=13),
         Section(section_name='Social', section_order=14),
         Section(section_name='Social Reporting', section_order=15),
         Section(section_name='Terms', section_order=16),
         Section(section_name='UI/UX Notifications', section_order=17),
         Section(section_name='UI/UX: Basics', section_order=18),
         Section(section_name='UI/UX: Bulk edits', section_order=19),
         Section(section_name='UI/UX: Campaign set up', section_order=20),
         Section(section_name='UI/UX: live campaign', section_order=21),
         Section(section_name='UI/UX: Margin Management ', section_order=22),
         Section(section_name='UI/UX: Pacing', section_order=23),
         Section(section_name='UI/UX: Pricing', section_order=24),
         Section(section_name='Video', section_order=25),
         Section(section_name='Video Reporting', section_order=26),

        ])
    
def bulk_add_questions():
    Question.objects.bulk_create([
        Question(eval_question_name="Are you able to prove an insurance minimum of $5,000,000", eval_section_id=26, question_order=1),
        Question(eval_question_name="Is all Advertiser data shared only within advertiser and not shared or aggregated across advertisers ", eval_section_id=26, question_order=2),
        Question(eval_question_name="Is there a signed NDA between Vivaki and Vendor", eval_section_id=26, question_order=3),
        Question(eval_question_name="In the event of discrepancy greater than 10%, can impressions for billing be based on ad server data", eval_section_id=26, question_order=4),
        Question(eval_question_name="Agree to idemnify VivaKi, Agency and Client based on vendor issues", eval_section_id=26, question_order=5),
        Question(eval_question_name="Can you agree to sequential liability", eval_section_id=26, question_order=6),
        Question(eval_question_name="Can you agree to net 60 vendor payment terms", eval_section_id=26, question_order=7),
        Question(eval_question_name="Can you deliver data feeds for finance and analytics daily", eval_section_id=26, question_order=8),
        Question(eval_question_name="Can you agree to Vivaki/Groupe Amended IAB 2.0 terms", eval_section_id=26, question_order=9),
        Question(eval_question_name="Can you agree that the DSP will not require consistent review of amendments and addendums based on beta products, additional product fees, etc.", eval_section_id=26, question_order=10),
        Question(eval_question_name="No additional Platform Fee minimums (i.e. minimum monthly spend,  Tech Fee as % of Media or alternatively minimum CPM).", eval_section_id=26, question_order=11),
        Question(eval_question_name="Can you agree that publicis agency has first right of refusal to manage campaign via self service vs vendor managed service?", eval_section_id=26, question_order=12),
        Question(eval_question_name="Do you support tech fees ", eval_section_id=26, question_order=13),
        Question(eval_question_name="Do you support % media fee", eval_section_id=26, question_order=14),
        Question(eval_question_name="If you have a proprietary DMP, are the DMP features included in the DSP terms", eval_section_id=26, question_order=15),
        Question(eval_question_name="Do you have business development services ", eval_section_id=11, question_order=16),
        Question(eval_question_name="Do you agree that the DSP is not owned by a competitive holding company (IPG, Omnicom, WPP)", eval_section_id=11, question_order=17),
        Question(eval_question_name="Do you have a proprietary ad server", eval_section_id=11, question_order=18),
        Question(eval_question_name="Do you have a priorietery pixel server", eval_section_id=11, question_order=19),
        Question(eval_question_name="Are all audience lists generated at advertiser-level and not shared across advertisers", eval_section_id=11, question_order=20),
        Question(eval_question_name="Does your platform have secure and nonsecure pixel creation", eval_section_id=11, question_order=21),
        Question(eval_question_name="Do you support Open RTB 2.2", eval_section_id=11, question_order=22),
        Question(eval_question_name="Do you support Open RTB 2.3 ", eval_section_id=11, question_order=23),
        Question(eval_question_name="Can we use Vivaki/Publicis negotiated data rates", eval_section_id=28, question_order=24),
        Question(eval_question_name="Can Vivaki use the DSP's negotiated rates or whoever has the best price", eval_section_id=28, question_order=25),
        Question(eval_question_name="Can we search change logs within the DSP for? Use case: if a campaign drops in delivery on a certain day we can go back in and see what was altered that day.", eval_section_id=28, question_order=26),
        Question(eval_question_name="Can we view change logs? Use case: if a campaign drops in delivery on a certain day we can go back in and see what was altered that day.", eval_section_id=28, question_order=27),
        Question(eval_question_name="Do you have a forecasting tool (will get into specifics under UI/UX section)", eval_section_id=28, question_order=28),
        Question(eval_question_name="Can we pull campaign reporting within the UI (will get into specifics under reporting?) ", eval_section_id=28, question_order=29),
        Question(eval_question_name="Do you provide invoicing/clearing house support", eval_section_id=13, question_order=30),
        Question(eval_question_name="Do you have reconciliation fees associated with a discrepancy between platform and SSP reported spend ", eval_section_id=13, question_order=31),
        Question(eval_question_name="Can we send month-end billing reports with all fees itemized out by breaking out components of gross media cost (gross cost, net media, data provider costs, tech fees, service fees, additional  verification, adserving, 3rd party tracker fees)", eval_section_id=13, question_order=32),
        Question(eval_question_name="Do you adhere to finance SLA of data certification two business days after month end", eval_section_id=13, question_order=33),
        Question(eval_question_name="Do you adhere to finance SLA to including financial accounting codes (CPE codes)", eval_section_id=13, question_order=34),
        Question(eval_question_name="Do you adhere to finance SLA to provide billing summary against Vivaki standard spec by 5 business days after month end ", eval_section_id=13, question_order=35),
        Question(eval_question_name="Do you adhere to finance SLA to provide clarity of each adjustment on billing summaries, prior to issuing bill", eval_section_id=13, question_order=36),
        Question(eval_question_name="Do you provide all accounts payable, including all financial tracking ids (ie: mbox camapign-product-estimate ids)", eval_section_id=13, question_order=37),
        Question(eval_question_name="Do you support 3rd party seats (BYO Seat) for open rtb exchanges: AdX, YAX, AppNexus. ", eval_section_id=13, question_order=38),
        Question(eval_question_name="If you support 3rd party seats for open rtb exchanges, does DSP provide clearing house support", eval_section_id=13, question_order=39),
        Question(eval_question_name="If you support 3rd party seats for open rtb exchanges, does DSP wave fees for additional clearing house support", eval_section_id=13, question_order=40),
        Question(eval_question_name="Can we enter % markup rates up to 5 decimal precision. This is necessary to avoid rounding errors for vendor and service tracking", eval_section_id=13, question_order=41),
        Question(eval_question_name="When DSP acts as a clearing house, does DSP agree to pay vendors (SSPs, data providers), under Vivaki's payment terms (ie: Net 45 days)", eval_section_id=13, question_order=42),
        Question(eval_question_name="Do you have a proprietary DMP", eval_section_id=14, question_order=43),
        Question(eval_question_name="If you have a proprietary DMP, is there an additional fee to use the DMP features", eval_section_id=14, question_order=44),
        Question(eval_question_name="Do you support S2S integrations", eval_section_id=14, question_order=45),
        Question(eval_question_name="Can we add additional CPM fees within the platform to represent the Adobe DMP mark-up", eval_section_id=14, question_order=46),
        Question(eval_question_name="Can we add additional CPM fees within the platform to represent the BlueKai DMP mark-up", eval_section_id=14, question_order=47),
        Question(eval_question_name="Can we target the Adobe DMP segments into the DSP and see a high match rate of 80%+", eval_section_id=14, question_order=48),
        Question(eval_question_name="Is Vivaki able to target Bluekai DMP segments into the DSP and see a high match rate of 80%+", eval_section_id=14, question_order=49),
        Question(eval_question_name="Can you piggyback the Adobe DMP tag ", eval_section_id=14, question_order=50),
        Question(eval_question_name="Can we piggyback the Bluekai DMP tag ", eval_section_id=14, question_order=51),
        Question(eval_question_name="Can you permission audience segments to a specific instance", eval_section_id=14, question_order=52),
        Question(eval_question_name="Can you permission audience segments to a specific advertiser ", eval_section_id=14, question_order=53),
        Question(eval_question_name="Can you apply data to dynamic creative decisioning", eval_section_id=14, question_order=54),
        Question(eval_question_name="Do you have probabilistic ID modeling", eval_section_id=14, question_order=55),
        Question(eval_question_name="Do you have deterministic ID modeling", eval_section_id=14, question_order=56),
        Question(eval_question_name="Can we pre- bid target based on weather conditions ", eval_section_id=14, question_order=57),
        Question(eval_question_name="Can we assign different creatives (dynamically target) based on weather conditions ", eval_section_id=14, question_order=58),
        Question(eval_question_name="Do you have social data (Facebook, Twitter, MySpace)", eval_section_id=14, question_order=59),
        Question(eval_question_name="Can we upload a whitelist", eval_section_id=28, question_order=60),
        Question(eval_question_name="Is your UI available as a self-service with uptime over 99%?", eval_section_id=28, question_order=61),
        Question(eval_question_name="Do creatives live at the advertiser level", eval_section_id=28, question_order=62),
        Question(eval_question_name="Can we archive creatives", eval_section_id=28, question_order=63),
        Question(eval_question_name="Can we archive pixels", eval_section_id=28, question_order=64),
        Question(eval_question_name="Are there notifications when there are known issues ", eval_section_id=28, question_order=65),
        Question(eval_question_name="Does your UI have universal search functionality", eval_section_id=28, question_order=66),
        Question(eval_question_name="When forecasting, does your platform show the number of segment pools the user falls under", eval_section_id=15, question_order=67),
        Question(eval_question_name="Can we estimate the number of cookies against multiple targeted pixels or audience attributes", eval_section_id=15, question_order=68),
        Question(eval_question_name="Does DSP show projected impression volume and spend based on first party data", eval_section_id=15, question_order=69),
        Question(eval_question_name="Can we project volume and spend numbers according to campaign settings", eval_section_id=15, question_order=70),
        Question(eval_question_name="Can we view price-volume curve for forecasting when layering on 3rd party data", eval_section_id=15, question_order=71),
        Question(eval_question_name="Can we view price-volume curve for forecasting when layering on geo targeting preferences", eval_section_id=15, question_order=72),
        Question(eval_question_name="Can we view price-volume curve for forecasting when layering on inventory source preferences", eval_section_id=15, question_order=73),
        Question(eval_question_name="Can you forecast clearing price by source", eval_section_id=15, question_order=74),
        Question(eval_question_name="Does the forecasting feature which includes all costs factored, including net media, data licensing fees, tech fees, service fees and any additional fees", eval_section_id=15, question_order=75),
        Question(eval_question_name="Does DSP support GRP/TRP planning in the UI", eval_section_id=15, question_order=76),
        Question(eval_question_name="Can we project impression volume and spend numbers based on a whitelist", eval_section_id=15, question_order=77),
        Question(eval_question_name="Can we project impression volume and spend numbers based on ad unit size", eval_section_id=15, question_order=78),
        Question(eval_question_name="Can we project impression volume and spend numbers based on browser", eval_section_id=15, question_order=79),
        Question(eval_question_name="Can we project impression volume and spend numbers based on carrier", eval_section_id=15, question_order=80),
        Question(eval_question_name="Can we project impression volume and spend numbers based on device type", eval_section_id=15, question_order=81),
        Question(eval_question_name="Can we project impression volume and spend numbers based on IAB category ", eval_section_id=15, question_order=82),
        Question(eval_question_name="Can we project impression volume and spend numbers based on language (user's device/browser language)", eval_section_id=15, question_order=83),
        Question(eval_question_name="Can we project impression volume and spend numbers based on viewability (according to IAB's definition of viewability)", eval_section_id=15, question_order=84),
        Question(eval_question_name="Can we project impression volume and spend numbers based on a 3rd party geo-targeting tool ", eval_section_id=15, question_order=85),
        Question(eval_question_name="Can we project impression volume and spend numbers by layering on city", eval_section_id=15, question_order=86),
        Question(eval_question_name="Can we project impression volume and spend numbers by layering on country", eval_section_id=15, question_order=87),
        Question(eval_question_name="Can we project impression volume and spend numbers by layering on DMA", eval_section_id=15, question_order=88),
        Question(eval_question_name="Can we project impression volume and spend numbers by layering on zip code", eval_section_id=15, question_order=89),
        Question(eval_question_name="Can we project impression volume and spend numbers by layering on DSP declared age group", eval_section_id=15, question_order=90),
        Question(eval_question_name="Can we project impression volume and spend numbers by layering on DSP-declared HHI", eval_section_id=15, question_order=91),
        Question(eval_question_name="Can we project impression volume and spend numbers by layering on second party (exchange declared) data segments", eval_section_id=15, question_order=92),
        Question(eval_question_name="Do you offer recommended bids according to the campaign parameters", eval_section_id=15, question_order=93),
        Question(eval_question_name="Do you support OCR in-demo planning ", eval_section_id=15, question_order=94),
        Question(eval_question_name="Do you support VCE in-demo planning ", eval_section_id=15, question_order=95),
        Question(eval_question_name="Do you support private marketplaces executed through a Deal ID", eval_section_id=22, question_order=96),
        Question(eval_question_name="Can we forecast impression volume and spend based on Deal ID", eval_section_id=22, question_order=97),
        Question(eval_question_name="Can we target masked URLs if necessary (eg: google anonymous sites, microsoft masked bins, yahoonetplus.com)", eval_section_id=30, question_order=98),
        Question(eval_question_name="Can we block masked URLs that Vivaki rejects (eg: google anonymous sites, microsoft masked bins, yahoonetplus.com)", eval_section_id=30, question_order=99),
        Question(eval_question_name="Can we copy over full campaign settings for an IO, campaign, creative", eval_section_id=30, question_order=100),
        Question(eval_question_name="Can we include or exclude contextual keywords", eval_section_id=30, question_order=101),
        Question(eval_question_name="Can we set and manage a default whitelist or blacklist across all instances, so a sitelist doesn't have to be uploaded for individual campaigns. (This is necessary for the vivaki verified whitelist)", eval_section_id=30, question_order=102),
        Question(eval_question_name="Can we schedule start and end dates for the future", eval_section_id=30, question_order=103),
        Question(eval_question_name="Can we select multiple conversion pixels", eval_section_id=30, question_order=104),
        Question(eval_question_name="Can we set a daily budget cap", eval_section_id=30, question_order=105),
        Question(eval_question_name="Can we set an IO budget cap", eval_section_id=30, question_order=106),
        Question(eval_question_name="Can we enter a bid amount", eval_section_id=30, question_order=107),
        Question(eval_question_name="Can we set a minimum bid", eval_section_id=30, question_order=108),
        Question(eval_question_name="Can we set a CPA bid type", eval_section_id=30, question_order=109),
        Question(eval_question_name="Can we set a CPC bid type", eval_section_id=30, question_order=110),
        Question(eval_question_name="Can we set a dynamic CPM bid type", eval_section_id=30, question_order=111),
        Question(eval_question_name="Can we set a budget by month", eval_section_id=30, question_order=112),
        Question(eval_question_name="Can we daypart targeting based on user time zones", eval_section_id=30, question_order=113),
        Question(eval_question_name="Can we set instance-wide default inventory targetting settings ", eval_section_id=30, question_order=114),
        Question(eval_question_name="Can we set a preferred vendor to do ID swap with.  Example, an Advertiser might use BlueKai DMP and want to prioritize those IDsi vs other data providers", eval_section_id=14, question_order=115),
        Question(eval_question_name="Can we set an unlimited budget instead of a dollar amount for large budget blast campaigns", eval_section_id=30, question_order=116),
        Question(eval_question_name="Can we set up multiple custom flights on a single placement", eval_section_id=30, question_order=117),
        Question(eval_question_name="Are you able to prevent ad collision (multiple ads on the same page at the same time)", eval_section_id=30, question_order=118),
        Question(eval_question_name="Are we able to set a campaign objective against a CPA or ROI based on conversion pixel extended data", eval_section_id=30, question_order=119),
        Question(eval_question_name="Can we target a user based on session depth", eval_section_id=30, question_order=120),
        Question(eval_question_name="Can we target by gender", eval_section_id=30, question_order=121),
        Question(eval_question_name="Can we target by HHI", eval_section_id=30, question_order=122),
        Question(eval_question_name="Can we target by language", eval_section_id=30, question_order=123),
        Question(eval_question_name="Can we target sites according to quality rating as declared by DSP, SSP or publisher", eval_section_id=30, question_order=124),
        Question(eval_question_name="Can your ad server do A/B creative testing via segmented user pools (only see user A or B)", eval_section_id=30, question_order=125),
        Question(eval_question_name="Can your ad server do sequential messaging", eval_section_id=30, question_order=126),
        Question(eval_question_name="Can we detect and block illegal third party pixel fires", eval_section_id=30, question_order=127),
        Question(eval_question_name="Can we duplicate creatives", eval_section_id=30, question_order=128),
        Question(eval_question_name="Is there a checkbox indicating whether your DSP or Vivaki has payment liability", eval_section_id=30, question_order=129),
        Question(eval_question_name="Is there advanced daypart targeting with higher/lower % bids during target periods", eval_section_id=30, question_order=130),
        Question(eval_question_name="Does your DSP have auto detection of non-approved vendor pixels in order to verify if any pixels will cause a creative rejection", eval_section_id=30, question_order=131),
        Question(eval_question_name="Do you support brand studies", eval_section_id=30, question_order=132),
        Question(eval_question_name="Do you support bulk pixel creation. Eg: the ability to create more than one user id/segment pool at a time", eval_section_id=30, question_order=133),
        Question(eval_question_name="Do you support bulk pixel export. Eg: the ability to export many pizels at the same time, so a user does not have to pull them one by one", eval_section_id=30, question_order=134),
        Question(eval_question_name="Do you have a direct integration with a data partner in order to create custom segments directly within the data provider's UI that automatically ports into the DSP", eval_section_id=30, question_order=135),
        Question(eval_question_name="Does your UI show campaign status filters indicating whether a campaign is live, paused, deactivated or inactive", eval_section_id=30, question_order=136),
        Question(eval_question_name="Can you support at least two additional vendor cost fields", eval_section_id=30, question_order=137),
        Question(eval_question_name="Do you provide clear documentation indiciating targeting limits against entities (eg: 20K sites, 50K keywords, 10K zipcodes)", eval_section_id=30, question_order=138),
        Question(eval_question_name="Are we able to preview a companion banner in the UI", eval_section_id=30, question_order=139),
        Question(eval_question_name="Can a creative be assigned to multiple campaigns?", eval_section_id=30, question_order=140),
        Question(eval_question_name="Does a creative have to be versioned out to share across campaigns", eval_section_id=30, question_order=141),
        Question(eval_question_name="Do you support creative tag QA in the UI", eval_section_id=30, question_order=142),
        Question(eval_question_name="Can we daypart by hour", eval_section_id=30, question_order=143),
        Question(eval_question_name="Does your DSP have brand safety ratings available in the UI", eval_section_id=30, question_order=144),
        Question(eval_question_name="Can we frequency target at a weekly basis at the line item level", eval_section_id=30, question_order=145),
        Question(eval_question_name="Can we frequency target at a daily basis at the line item level", eval_section_id=30, question_order=146),
        Question(eval_question_name="Can we frequency target at a monthly basis at the line item level", eval_section_id=30, question_order=147),
        Question(eval_question_name="Do you support hierarchy rules for budgets (eg: child inherits parent settings)", eval_section_id=30, question_order=148),
        Question(eval_question_name="Do you support  hierarchy rules for inventory targeting (eg: child inherits parent settings)", eval_section_id=30, question_order=149),
        Question(eval_question_name="Are we able to optimize towards sites based on historical performance", eval_section_id=30, question_order=150),
        Question(eval_question_name="Can we set instance-wide default data fees, so camapign will inherit the data settings upon setup", eval_section_id=30, question_order=151),
        Question(eval_question_name="Can we set instance-wide default geos, so camapign will inherit the data settings upon setup", eval_section_id=30, question_order=152),
        Question(eval_question_name="Can we set instance-wide default margin settings, so camapign will inherit the data settings upon setup", eval_section_id=30, question_order=153),
        Question(eval_question_name="Can we target a data segment using segment ID", eval_section_id=30, question_order=154),
        Question(eval_question_name="Can we target a data segment using segment name", eval_section_id=30, question_order=155),
        Question(eval_question_name="Does the DSP support an ad creative wizard", eval_section_id=30, question_order=156),
        Question(eval_question_name="Does the DSP pass a DSP auction ID (use case: detailed inventory analysis)", eval_section_id=30, question_order=157),
        Question(eval_question_name="Do you pass DSP campaign and publisher macros through ad verification tags", eval_section_id=30, question_order=158),
        Question(eval_question_name="Do you have suggested pacing/daily spend visibility in the UI", eval_section_id=30, question_order=159),
        Question(eval_question_name="Do you support basic dynamic creative integration (tag wrapping)", eval_section_id=30, question_order=160),
        Question(eval_question_name="Do you provide basic ad verification integration via ag wrapping within the UI for Display", eval_section_id=30, question_order=161),
        Question(eval_question_name="Do you provide basic ad verification integration via tag wrapping within the UI for Video", eval_section_id=30, question_order=162),
        Question(eval_question_name="Do you have a UI integration with brand study partners so a user is able to run a brand study without manually appending brand study tracking or tags", eval_section_id=30, question_order=163),
        Question(eval_question_name="Do you allow users to make changes to be applied retroactive, so that it does not overwrite moving forward. Use case: if a data provider fee was entered incorrectly you could have it fixed retroactively to make billing cleaner", eval_section_id=32, question_order=164),
        Question(eval_question_name="Do you allow for changes made to only take effect moving forward. Use Case:  If margins were changed this month and you pull a report for last month, last month will reflect the old numbers.)", eval_section_id=32, question_order=165),
        Question(eval_question_name="Can we manage a campaign against a fixed CPM", eval_section_id=34, question_order=166),
        Question(eval_question_name="Can we manage a campaign against a flat (fixed) cost per acquisition (CPA), using client ad server figures", eval_section_id=34, question_order=167),
        Question(eval_question_name="Can we manage campaigns against a flat (fixed) cost per completed view (CPCV)", eval_section_id=34, question_order=168),
        Question(eval_question_name="Does you have a rate card for different demo audiences", eval_section_id=34, question_order=169),
        Question(eval_question_name="Does you support Cost Per Point based on Comscore VCE", eval_section_id=34, question_order=170),
        Question(eval_question_name="Do you support Cost Per Point based on Nielson OCR", eval_section_id=34, question_order=171),
        Question(eval_question_name="Can you show pacing based on campaign budgets in graph form", eval_section_id=33, question_order=172),
        Question(eval_question_name="Can you show pacing based on campaign budgets in numerical (%) form", eval_section_id=33, question_order=173),
        Question(eval_question_name="Can we manage against in-demo guarantees using Comscore vCE", eval_section_id=33, question_order=174),
        Question(eval_question_name="Does your DSP support the ability to manage campaign against in-demo guarantees using Nielson OCR", eval_section_id=33, question_order=175),
        Question(eval_question_name="Do you support the ability to pace evenly throughout the campaigns duration", eval_section_id=33, question_order=176),
        Question(eval_question_name="Do you support the ability to pace evenly throughout the day", eval_section_id=33, question_order=177),
        Question(eval_question_name="Do you support the ability to pace evenly throughout the week", eval_section_id=33, question_order=178),
        Question(eval_question_name="Do you support the ability to pace evenly throughout the month", eval_section_id=33, question_order=179),
        Question(eval_question_name="Can we report out on pacing to see if the campaign is over or under pacing ", eval_section_id=33, question_order=180),
        Question(eval_question_name="Can we see bid clearing price for a particular inventory source/line item", eval_section_id=33, question_order=181),
        Question(eval_question_name="Can we set campaign/line item level ASAP delivery for campaigns with 1-2 day blasts", eval_section_id=33, question_order=182),
        Question(eval_question_name="Can we set IO level ASAP delivery instead of evenly for campaigns with 1-2 day blasts", eval_section_id=33, question_order=183),
        Question(eval_question_name="Can we view pacing, performance and remaining budget at the advertiser level", eval_section_id=33, question_order=184),
        Question(eval_question_name="Can we view pacing, performance and remaining budget at the Line Item/Campaign level", eval_section_id=33, question_order=185),
        Question(eval_question_name="Is there a product data feed to inform creative instructions for DCO campaigns", eval_section_id=31, question_order=186),
        Question(eval_question_name="Do you have the ability to track DSP creative ID and creative name to exchange creative ID and name", eval_section_id=31, question_order=187),
        Question(eval_question_name="Do you support advertiser remarketing pixel targeting", eval_section_id=31, question_order=188),
        Question(eval_question_name="Do you support AND logic for multiple ID/segment combinations", eval_section_id=31, question_order=189),
        Question(eval_question_name="Do you provide auto-segmentation or optimization", eval_section_id=31, question_order=190),
        Question(eval_question_name="Do you provide creative approvals ", eval_section_id=31, question_order=191),
        Question(eval_question_name="Do you provide flags on inventory", eval_section_id=31, question_order=192),
        Question(eval_question_name="Are we able to include/exclude pixels", eval_section_id=31, question_order=193),
        Question(eval_question_name="Do changes to campaign settings take effect immediately within 15 minutes", eval_section_id=31, question_order=194),
        Question(eval_question_name="Do you have NOT logic support for multiple ID/segment combinations", eval_section_id=31, question_order=195),
        Question(eval_question_name="Do you have AND logic for multiple ID/segment combinations", eval_section_id=31, question_order=196),
        Question(eval_question_name="Do you have OR logic for multiple ID/segment combinations", eval_section_id=31, question_order=197),
        Question(eval_question_name="Are remarketing pools based on DSP pixel updated within an hour of the pixel event", eval_section_id=31, question_order=198),
        Question(eval_question_name="Are remarketing pools based on DSP pixel updated within 4 hours of the pixel event", eval_section_id=31, question_order=199),
        Question(eval_question_name="Are remarketing pools based on DSP pixel updated within 12 hours of the pixel event", eval_section_id=31, question_order=200),
        Question(eval_question_name="Do you have a screenshot finder/generator to show screenshots of an ad on a live page", eval_section_id=31, question_order=201),
        Question(eval_question_name="Do you support short form videos", eval_section_id=35, question_order=202),
        Question(eval_question_name="Do you support long form videos", eval_section_id=35, question_order=203),
        Question(eval_question_name="Does your platform provide player-size targeting (small vs. medium vs. large)", eval_section_id=35, question_order=204),
        Question(eval_question_name="Does your platform provide player-state targeting (user initiated vs.auto-play)", eval_section_id=35, question_order=205),
        Question(eval_question_name="Does your DSP allow for user to upload video creatives ", eval_section_id=35, question_order=206),
        Question(eval_question_name="Can we target ATF vs. BTF ", eval_section_id=35, question_order=207),
        Question(eval_question_name="Can we target in-stream video", eval_section_id=35, question_order=208),
        Question(eval_question_name="Do you support Vast 2.0", eval_section_id=35, question_order=209),
        Question(eval_question_name="Do you support Vast 3.0", eval_section_id=35, question_order=210),
        Question(eval_question_name="Do you support VPAID", eval_section_id=35, question_order=211),
        Question(eval_question_name="Do you support VPAID Inventory targeting", eval_section_id=35, question_order=212),
        Question(eval_question_name="Do you support VAST inventory targeting ", eval_section_id=35, question_order=213),
        Question(eval_question_name="Can we target Android Apps", eval_section_id=16, question_order=214),
        Question(eval_question_name="Can we target iOS Apps", eval_section_id=16, question_order=215),
        Question(eval_question_name="Can we target by App Name in DSP", eval_section_id=16, question_order=216),
        Question(eval_question_name="Can we target by App Store ID in DSP", eval_section_id=16, question_order=217),
        Question(eval_question_name="Can we target by Carrier (Verizon vs. AT&T)", eval_section_id=16, question_order=218),
        Question(eval_question_name="Can we target by Device Manufacturer", eval_section_id=16, question_order=219),
        Question(eval_question_name="Can we target by Device Model", eval_section_id=16, question_order=220),
        Question(eval_question_name="Can we target b device type (smartphone, tablet)", eval_section_id=16, question_order=221),
        Question(eval_question_name="Can we target by OS version", eval_section_id=16, question_order=222),
        Question(eval_question_name="Can we target Mobile Web only", eval_section_id=16, question_order=223),
        Question(eval_question_name="Do you support MRAID", eval_section_id=16, question_order=224),
        Question(eval_question_name="Can we preview Mobile creatives in the UI", eval_section_id=16, question_order=225),
        Question(eval_question_name="Can we preview Mobile creatives in the UI", eval_section_id=16, question_order=226),
        Question(eval_question_name="Able to target location by geo-fencing", eval_section_id=16, question_order=227),
        Question(eval_question_name="Able to target by place-based radius targeting directly through DSP", eval_section_id=16, question_order=228),
        Question(eval_question_name="Able to target by place-based radius targeting through Factual", eval_section_id=16, question_order=229),
        Question(eval_question_name="Supports mobile video inventory ", eval_section_id=16, question_order=230),
        Question(eval_question_name="Do you support device fingerprinting with a high statistical match", eval_section_id=16, question_order=231),
        Question(eval_question_name="Can we version out and scale facebook user page post ads", eval_section_id=24, question_order=232),
        Question(eval_question_name="Can we version out facebook ads per various demos (age, gender, etc)", eval_section_id=24, question_order=233),
        Question(eval_question_name="Can we version out fb ads per geos", eval_section_id=24, question_order=234),
        Question(eval_question_name="Can we auto optimize by FB page likes", eval_section_id=24, question_order=235),
        Question(eval_question_name="Can we auto optimize by FB app installs", eval_section_id=24, question_order=236),
        Question(eval_question_name="Can we auto optimize by FB advertiser website clicks", eval_section_id=24, question_order=237),
        Question(eval_question_name="Can we auto optimize by FB advertiser website conversions", eval_section_id=24, question_order=238),
        Question(eval_question_name="Can we auto optimize by FB canvas app engagement", eval_section_id=24, question_order=239),
        Question(eval_question_name="Can we auto optimize by FB canvas app installs", eval_section_id=24, question_order=240),
        Question(eval_question_name="Can we auto optimize by FB event responses", eval_section_id=24, question_order=241),
        Question(eval_question_name="Can we auto optimize by FB mobile app engagement", eval_section_id=24, question_order=242),
        Question(eval_question_name="Can we aut optimize by FB offer claims", eval_section_id=24, question_order=243),
        Question(eval_question_name="Can we auto optimize by twitter added followers ", eval_section_id=24, question_order=244),
        Question(eval_question_name="Can we auto optimize by Twitter Engagement", eval_section_id=24, question_order=245),
        Question(eval_question_name="TV Sync capabilities for Facebook", eval_section_id=24, question_order=246),
        Question(eval_question_name="TV Sync capabilities for Twitter", eval_section_id=24, question_order=247),
        Question(eval_question_name="Social Search targeting for Facebook", eval_section_id=24, question_order=248),
        Question(eval_question_name="Targeting Recommendations: Links to Facebook's own system", eval_section_id=24, question_order=249),
        Question(eval_question_name="Targeting Recommendations: Recommends Facebook interests based on affinity indexing", eval_section_id=24, question_order=250),
        Question(eval_question_name="Targeting Recommendations: Recommends Facebook interests based on theme", eval_section_id=24, question_order=251),
        Question(eval_question_name="Targeting Recommendations: Recommends Twitter interests based on affinity indexing", eval_section_id=24, question_order=252),
        Question(eval_question_name="Targeting Recommendations: Recommends Twitter interests based on theme", eval_section_id=24, question_order=253),
        Question(eval_question_name="Supports Facebook custom audiences, 3rd party data segements (BlueKai, Datalogix, etc)", eval_section_id=24, question_order=254),
        Question(eval_question_name="Supports Facebook custom audiences, 1st party PII user lists.  Vendor must support VivaKi required process where VivaKi does not handle PII, where other Client agent can upload PII into vendor system for VivaKi to access the Facebook custom audience aggregated segment", eval_section_id=24, question_order=255),
        Question(eval_question_name="Create dynamic custom audiences based on search clicks. Integration with Kenshoo Search", eval_section_id=24, question_order=256),
        Question(eval_question_name="Is a user able to paste page post ID to a select post", eval_section_id=24, question_order=257),
        Question(eval_question_name="Does your platform provide facebook page post management", eval_section_id=24, question_order=258),
        Question(eval_question_name="Does your platform provide facebook page post management: the quality of page post specific screens", eval_section_id=24, question_order=259),
        Question(eval_question_name="Does your platform have a social creative image library allowing free usage of images", eval_section_id=24, question_order=260),
        Question(eval_question_name="Does your platform have a social targeting library for canned attributes or segments", eval_section_id=24, question_order=261),
        Question(eval_question_name="Do you provide alerts when there are delivery issues for social ads", eval_section_id=24, question_order=262),
        Question(eval_question_name="Do you have social search targeting for twitter", eval_section_id=24, question_order=263),
        Question(eval_question_name="Do you support click tag tracking on Facebook", eval_section_id=24, question_order=264),
        Question(eval_question_name="Do you support click tag tracking on twitter", eval_section_id=24, question_order=265),
        Question(eval_question_name="Do you support view tag tracking on facebook", eval_section_id=24, question_order=266),
        Question(eval_question_name="Can you support in-feed article units", eval_section_id=18, question_order=267),
        Question(eval_question_name="Can you support in-feed image units", eval_section_id=18, question_order=268),
        Question(eval_question_name="Are you integrated with native SSPs", eval_section_id=18, question_order=269),
        Question(eval_question_name="Can you customize the in-feed header and text within the platform", eval_section_id=18, question_order=270),
        Question(eval_question_name="Can we target recommendation widgets (eg: Taboola, Outbrain)", eval_section_id=18, question_order=271),
        Question(eval_question_name="Can we forecast on native inventory ", eval_section_id=18, question_order=272),
        Question(eval_question_name="Can use IP address for cross-device targeting within the same household ", eval_section_id=20, question_order=273),
        Question(eval_question_name="Can you automatically re-allocate budgets between strategies, ad format and device", eval_section_id=20, question_order=274),
        Question(eval_question_name="Are we able to bulk edit targeting to add or remove select line items", eval_section_id=29, question_order=275),
        Question(eval_question_name="Are we able to make bulk changes to average CPM", eval_section_id=29, question_order=276),
        Question(eval_question_name="Are we able to make bulk changes to budget", eval_section_id=29, question_order=277),
        Question(eval_question_name="Are we able to make bulk changes to frequency capping", eval_section_id=29, question_order=278),
        Question(eval_question_name="Are we able to make bulk changes to targeting deal ids", eval_section_id=29, question_order=279),
        Question(eval_question_name="are we able to make bulk changes to targeting inventory by SSP", eval_section_id=29, question_order=280),
        Question(eval_question_name="Are we able to make bulk changes to targeting inventory whitelists", eval_section_id=29, question_order=281),
        Question(eval_question_name="Do you provide formal notifications for budget server failures/delays explaining the issue and how it affects campaigns", eval_section_id=27, question_order=282),
        Question(eval_question_name="Do you provide formal notifications for pixel server failures/delays explaining the issue and how it affects campaigns", eval_section_id=27, question_order=283),
        Question(eval_question_name="If pixel, budget issues occur, do you provide a list of impacted campaigns ", eval_section_id=27, question_order=284),
        Question(eval_question_name="Will you provide a detailed pixel implementation guide based on 3PAS container. This would include instructions on how platform pixel needs to be manipulated within UAT or floodlight", eval_section_id=23, question_order=285),
        Question(eval_question_name="Will you provide a training module for basic planning, campaign setup and reporting", eval_section_id=23, question_order=286),
        Question(eval_question_name="Do you have maintained API documentation, including mapping of translations of fields between what is exposed in the UI vs. API", eval_section_id=23, question_order=287),
        Question(eval_question_name="Are there maintained in-line definitions for billing fields", eval_section_id=23, question_order=288),
        Question(eval_question_name="Is there a maintained knowledge-base showing definitions for billing fields", eval_section_id=23, question_order=289),
        Question(eval_question_name="Are there maintained in-line definitions for metrics", eval_section_id=23, question_order=290),
        Question(eval_question_name="Is there a maintained knowledge-base showing metric definitions, including itemized costs", eval_section_id=23, question_order=291),
        Question(eval_question_name="Are there maintained in-line defiitions explaining fields in the UI?", eval_section_id=23, question_order=292),
        Question(eval_question_name="Is there a maintained knowledge base explaining fields in the UI ", eval_section_id=23, question_order=293),
        Question(eval_question_name="Is there maintained logfile documentation and fields showing the mapping/translation of fields that are exposed in the logfile", eval_section_id=23, question_order=294),
        Question(eval_question_name="Can we report out on completion rate", eval_section_id=36, question_order=295),
        Question(eval_question_name="Can we pull GRP and CPP reporting based on OCR or VCE panels", eval_section_id=36, question_order=296),
        Question(eval_question_name="Do you support vCE in-demo reporting in the UI", eval_section_id=36, question_order=297),
        Question(eval_question_name="Can we pull video completed metrics", eval_section_id=36, question_order=298),
        Question(eval_question_name="Can we report out at the youtube channel level", eval_section_id=36, question_order=299),
        Question(eval_question_name="Can we report out on geo-attribution", eval_section_id=17, question_order=300),
        Question(eval_question_name="Can we pull reporting based on GEOs", eval_section_id=17, question_order=301),
        Question(eval_question_name="Do you support Placed attribution integration", eval_section_id=17, question_order=302),
        Question(eval_question_name="Can we report out on native inventory", eval_section_id=18, question_order=303),
        Question(eval_question_name="Can we report out on facebook page likes", eval_section_id=25, question_order=304),
        Question(eval_question_name="Can we report out on facebook mobile app installs", eval_section_id=25, question_order=305),
        Question(eval_question_name="Can we report out on Facebook advertiser website clicks", eval_section_id=25, question_order=306),
        Question(eval_question_name="Can we report out on Facebook advertiser website conversions", eval_section_id=25, question_order=307),
        Question(eval_question_name="Can we report out on Facebook canvas app engagement", eval_section_id=25, question_order=308),
        Question(eval_question_name="Can we report out on Facebook canvas app installs", eval_section_id=25, question_order=309),
        Question(eval_question_name="Can we report out on Facebook event responses", eval_section_id=25, question_order=310),
        Question(eval_question_name="Can we report out on Facebook mobile app engagement", eval_section_id=25, question_order=311),
        Question(eval_question_name="Can we report out on Facebook offer claims", eval_section_id=25, question_order=312),
        Question(eval_question_name="Can we report out on twitter added followers", eval_section_id=25, question_order=313),
        Question(eval_question_name="Can we report out on twitter engagement", eval_section_id=25, question_order=314),
        Question(eval_question_name="Do we have access to FB insights API", eval_section_id=25, question_order=315),
        Question(eval_question_name="Do we have access to FB Social Graph API", eval_section_id=25, question_order=316),
        Question(eval_question_name="Do we have access to Twitter insights API", eval_section_id=25, question_order=317),
        Question(eval_question_name="Can we pull FB newsfeed metrics", eval_section_id=25, question_order=318),
        Question(eval_question_name="Can we report on rate comment/engagement sentimement through another API partner", eval_section_id=25, question_order=319),
        Question(eval_question_name="Do you have a reporting integration with Nielson OCR for FB audience reporting", eval_section_id=25, question_order=320),
        Question(eval_question_name="Can we pull channel specific unique reach", eval_section_id=21, question_order=321),
        Question(eval_question_name="Can we pull cross-channel unique reach", eval_section_id=21, question_order=322),
        Question(eval_question_name="Can we pull cross-channel path to conversion reporting", eval_section_id=21, question_order=323),
        Question(eval_question_name="Can we report out on 3rd party data cost separate from media cost", eval_section_id=12, question_order=324),
        Question(eval_question_name="Can you report out custom data values (i.e. including product IDs, shopping cart/checkout value, etc)", eval_section_id=12, question_order=325),
        Question(eval_question_name="Can we customize the time period for a report", eval_section_id=12, question_order=326),
        Question(eval_question_name="Can we save a query", eval_section_id=12, question_order=327),
        Question(eval_question_name="Can we edit a saved query", eval_section_id=12, question_order=328),
        Question(eval_question_name="Can we measure online delivery to offline sales data/lift via 3rd party vendor data", eval_section_id=12, question_order=329),
        Question(eval_question_name="Can we measure online delivery to offline sales data/lift via proprietery data", eval_section_id=12, question_order=330),
        Question(eval_question_name="Can we measure online delivery to online sales data/lift via 3rd party vendor data", eval_section_id=12, question_order=331),
        Question(eval_question_name="Can we measure online delivery to online sales data/lift via proprietary data", eval_section_id=12, question_order=332),
        Question(eval_question_name="Can we modify an existing saved query and resave the new settings", eval_section_id=12, question_order=333),
        Question(eval_question_name="Can we pull conversion reporting for the prior day", eval_section_id=12, question_order=334),
        Question(eval_question_name="Can we pull conversion reporting with the same day within 4 hours", eval_section_id=12, question_order=335),
        Question(eval_question_name="Can we pull delivery reporting for the prior day, including impressions, clicks and itemized costs", eval_section_id=12, question_order=336),
        Question(eval_question_name="Can we pull delivery reporting for the same day within 4 hours, including impressions, clicks and itemized costs", eval_section_id=12, question_order=337),
        Question(eval_question_name="Can we pull pixel loads for the prior day", eval_section_id=12, question_order=338),
        Question(eval_question_name="Can we pull pixel loads for the same day within 4 hours", eval_section_id=12, question_order=339),
        Question(eval_question_name="Can we pull reporting for the prior month ", eval_section_id=12, question_order=340),
        Question(eval_question_name="Can you schedule reports", eval_section_id=12, question_order=341),
        Question(eval_question_name="Can we report out on delivery at the zip code level", eval_section_id=12, question_order=342),
        Question(eval_question_name="Can we report out on conversions against remarketing pixel recency", eval_section_id=12, question_order=343),
        Question(eval_question_name="Can we report out new audience uniques", eval_section_id=12, question_order=344),
        Question(eval_question_name="Can we report out on the 3PAS placement ID entered at the creative level ", eval_section_id=12, question_order=345),
        Question(eval_question_name="Can we report out subexchange. This applies to AppNexus Exchange's inventory sources", eval_section_id=12, question_order=346),
        Question(eval_question_name="Can we report out on targeted 1st/3rd party audiences by day", eval_section_id=12, question_order=347),
        Question(eval_question_name="Can we report out on untargeted 1st/3rd party audiences by day", eval_section_id=12, question_order=348),
        Question(eval_question_name="Can we view PC and PV metrics separately", eval_section_id=12, question_order=349),
        Question(eval_question_name="Can we view multiple conversion metrics separately", eval_section_id=12, question_order=350),
        Question(eval_question_name="Can we set up a scheduled report on a daily interval", eval_section_id=12, question_order=351),
        Question(eval_question_name="Can we set up a scheduled report on a monthly interval", eval_section_id=12, question_order=352),
        Question(eval_question_name="Can we set up a saved report for other users, allowing other users to access and resave the new settings", eval_section_id=12, question_order=353),
        Question(eval_question_name="Can we use lookalike reporting to change targeting", eval_section_id=12, question_order=354),
        Question(eval_question_name="Do we have the ability to use Rentrak (i.e. for reporting campaign delivery to closed content viewership)", eval_section_id=12, question_order=355),
        Question(eval_question_name="Can we identify top referring Url for pixel loads", eval_section_id=12, question_order=356),
        Question(eval_question_name="Can we report delivery and performance by hour", eval_section_id=12, question_order=357),
        Question(eval_question_name="Can we report out by GEO", eval_section_id=12, question_order=358),
        Question(eval_question_name="Can we report out by creative", eval_section_id=12, question_order=359),
        Question(eval_question_name="Can we report out by line item", eval_section_id=12, question_order=360),
        Question(eval_question_name="Can we report out by site", eval_section_id=12, question_order=361),
        Question(eval_question_name="Can we report out by inventory source", eval_section_id=12, question_order=362),
        Question(eval_question_name="Can we report out on page-level content reporting (i.e. showing what content was on the page that the ad served on)", eval_section_id=12, question_order=363),
        Question(eval_question_name="Can we see the number of loads on a pixel by day", eval_section_id=12, question_order=364),
        Question(eval_question_name="Can we report out on the baked in fees including data provider, media, platform fee", eval_section_id=12, question_order=365),
        Question(eval_question_name="Can we view advanced metrics by quartile", eval_section_id=12, question_order=366),
        Question(eval_question_name="Can we explore 2nd and 3rd level affinities and understand the strength of their connection back to a source of interest (Social)", eval_section_id=12, question_order=367),
        Question(eval_question_name="Can we have time stamped campaign log file access which includes impressions, clicks and conversions", eval_section_id=12, question_order=368),
        Question(eval_question_name="Can we have time stamped campaign log file access which includes impressions, clicks and conversions at no addditional cost", eval_section_id=12, question_order=369),
        Question(eval_question_name="Can we have time stamped campaign log file access showing auction ID", eval_section_id=12, question_order=370),
        Question(eval_question_name="Can we have time stamped campaign log file access showing user ID, geo, ip address", eval_section_id=12, question_order=371),
        Question(eval_question_name="Can we report out on verticals/channels within an exchange", eval_section_id=12, question_order=372),
        Question(eval_question_name="Can we report out on delivery for companion banners (impressions, clicks)", eval_section_id=12, question_order=373),
        Question(eval_question_name="Is there 12 month data warehousing of campaign delivery and performance at no additional cost", eval_section_id=12, question_order=374),
        Question(eval_question_name="Is there 18 month data warehousing of campaign delivery and performance at no additional cost", eval_section_id=12, question_order=375),
        Question(eval_question_name="Is there infinite data warehousing of campaign delivery and performance at no additional cost", eval_section_id=12, question_order=376),
        Question(eval_question_name="Can we pull daily reporting for impressions, clicks, spend, conversions at the advertiser level", eval_section_id=12, question_order=377),
        Question(eval_question_name="Can we pull aggregate monthly reporting for impressions, clicks, spend, conversions at the advertiser level", eval_section_id=12, question_order=378),
        Question(eval_question_name="Can we pull reporting for impressions, clicks, spend, conversions for a customized time frame at the advertiser level", eval_section_id=12, question_order=379),
        Question(eval_question_name="Can we pull daily reporting for impressions, clicks, spend, conversions at the IO level", eval_section_id=12, question_order=380),
        Question(eval_question_name="Can we pull aggregate monthly reporting for impressions, clicks, spend, conversions at the IO level", eval_section_id=12, question_order=381),
        Question(eval_question_name="Do we have insight into algorithmically determined changes", eval_section_id=12, question_order=382),
        Question(eval_question_name="Can we pull daily reporting for impressions, clicks, spend, conversions at the line item level", eval_section_id=12, question_order=383),
        Question(eval_question_name="Can we pull monthly reporting for impressions, clicks, spend, conversions at the line item level", eval_section_id=12, question_order=384),
        Question(eval_question_name="Can we pull reporting for impressions, clicks, spend, conversions for a customized time frame at the line item level", eval_section_id=12, question_order=385),
        Question(eval_question_name="Can we pull look alike audience reporting against a live campaign", eval_section_id=12, question_order=386),
        Question(eval_question_name="Can we pull lookalike reporting against pixels by a custom time period", eval_section_id=12, question_order=387),
        Question(eval_question_name="Can we pull OCR in-demo reporting in the UI", eval_section_id=12, question_order=388),
        Question(eval_question_name="Can we pull VCE in-demo reporting in the UI", eval_section_id=12, question_order=389),
        Question(eval_question_name="Do we have pull pixel log file access", eval_section_id=12, question_order=390),
        Question(eval_question_name="Can we pull pixel uniques/cookie reporting", eval_section_id=12, question_order=391),
        Question(eval_question_name="Do we have predefined multi-touch attribution reporting in the UI dashboard", eval_section_id=12, question_order=392),
        Question(eval_question_name="Can we set predefined timeframe to conversion reporting", eval_section_id=12, question_order=393),
        Question(eval_question_name="Can we pull reach/frequency reporting that is panel-based (not solely cookie-based)", eval_section_id=12, question_order=394),
        Question(eval_question_name="Do you have a report builder that can select across DSP instances for all advertisers/IOs/Line Items", eval_section_id=12, question_order=395),
        Question(eval_question_name="Do you have a report builder that can select all advertisers/IOs/Line Items within a single DSP instance", eval_section_id=12, question_order=396),
        Question(eval_question_name="Do you have a report builder to send a scheduled report to specific email addresses", eval_section_id=12, question_order=397),
        Question(eval_question_name="Can you support brand measurement in order to optimize towards in-banner survey responses (nielson vizu, dimestore, dynamic logic, etc)", eval_section_id=12, question_order=398),
        Question(eval_question_name="Can you support brand measurement based on proprietary lift (i.e. through searches, page views, product views etc)", eval_section_id=12, question_order=399),
        Question(eval_question_name="Can we report out multiple layers in one report", eval_section_id=12, question_order=400),


    ])